repos:
  - repo: local
    hooks:
      - id: trufflehog
        name: TruffleHog
        description: Detect secrets in your data.
        entry: bash -c 'docker run --rm -v "$(pwd):/dotfiles" -i trufflesecurity/trufflehog:latest git file:///dotfiles --since-commit HEAD --fail'
        language: system
        stages: ["pre-commit", "pre-push"]
        pass_filenames: false
